# Generated by Django 5.2.5 on 2025-08-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Messaggio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data di invio')),
            ],
            options={
                'verbose_name': 'Messaggio di contatto',
                'verbose_name_plural': 'Messaggi di contatto',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Immagine')),
                ('url', models.URLField(blank=True, verbose_name='URL del progetto')),
                ('github_url', models.URLField(blank=True, verbose_name='URL GitHub')),
                ('technologies', models.CharField(max_length=200, verbose_name='Tecnologie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data di creazione')),
            ],
            options={
                'verbose_name': 'Progetto',
                'verbose_name_plural': 'Progetti',
            },
        ),
    ]
